version: 2

env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - binary: markscribe
    flags:
      - -trimpath
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - linux
      - freebsd
      - openbsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7

archives:
  - format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm }}v{{ . }}{{ end }}

nfpms:
  - ids:
      - markscribe
    vendor: muesli
    homepage: "https://fribbledom.com/"
    maintainer: "Christian Muehlhaeuser <muesli@gmail.com>"
    description: "Your personal markdown scribe with template-engine and Git(Hub) & RSS powers"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

homebrew_casks:
  - repository:
      owner: muesli
      name: homebrew-tap
    commit_author:
      name: "Christian Muehlhaeuser"
      email: "muesli@gmail.com"
    homepage: "https://fribbledom.com/"
    description: "Your personal markdown scribe with template-engine and Git(Hub) & RSS powers"
    # skip_upload: true

signs:
  - artifacts: checksum

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
